#!/bin/bash

echo "Welcome Adventurer!" 
read -p "What is your name? " name


age_check(){
echo "You approach a tavern."
read -p "The Orc asks you how old you are. " age

 if (($age >= 21))

 then
	 echo "The Orc lets you pass"
	 return 1
 else 
	 echo "You may not enter the tavern, little one"
	 return 0

 fi

}

age_check
tavernpass=$?

climb_window(){
 if (($tavernpass == 0))
 then 
 	echo "You notice a window on the ground floor. You climb through it."
 fi
}

tavern_chrcheck(){
 if (($tavernpass == 0))
 then 
 	read -p "$name do you want to roll a charisma check? yes/no " answer
	if [ "$answer" == "yes" ]
	then 
		local chr=$(( $RANDOM % 10))
		echo "You rolled a $chr"
		if (($chr >= 5))
		then
			echo "You tell the orc you are the chimney sweep. He allows you to enter."
			return 1
		else
			echo "You claim that you work there. The orc does not believe you."
			climb_window
			return 0
		fi

	else [ "$answer" == "no" ]
		climb_window
		return 0
	fi
 
 else
	echo "You enter the tavern"
 fi
}

tavern_chrcheck
tavern_chrfail=$?

tavern_stealthcheck(){

 echo "Roll a stealth check"
 local stealth=$(( $RANDOM % 10))
 echo "You rolled a $stealth"
 if (($stealth >= 5))
 then
 	echo "No one notices you enter"
 else
	echo "The cook sees you. He thinks you are the dishwasher. You wash dishes for three hours. You receive five gold."
	gold=5
 fi
}

in_tavern(){
echo "Roll for int to look around the tavern"
}	


if (($tavernpass == 0))
then tavern_stealthcheck
else in_tavern
fi






