#!/bin/bash

echo "Welcome Adventurer!" 
read -p "What is your name? " name


age_check(){
echo "You approach a tavern."
read -p "The Orc asks you how old you are. " age

 if (($age >= 21))

 then
	 echo "The Orc lets you pass"
	 return 1
 else 
	 echo "You may not enter the tavern, little one"
	 return 0

 fi

}

age_check
tavernpass=$?

climb_window(){
 if (($tavernpass == 0))
 then 
 	echo "You notice a window on the ground floor. You climb through it."
 fi
}

tavern_chrcheck(){
 if (($tavernpass == 0))
 then 
 	read -p "$name do you want to roll a charisma check? yes/no " answer
	if [ "$answer" == "yes" ]
	then 
		local chr=$(( $RANDOM % 10))
		echo "You rolled a $chr"
		if (($chr >= 5))
		then
			echo "You tell the orc you are the chimney sweep. He allows you to enter."
			return 1
		else
			echo "You claim that you work there. The orc does not believe you."
			climb_window
			return 0
		fi

	else [ "$answer" == "no" ]
		climb_window
		return 0
	fi
 
 else
	echo "You enter the tavern"
 fi
}

tavern_chrcheck
tavern_chrfail=$?

tavern_stealthcheck(){

 echo "Roll a stealth check"
 local stealth=$(( $RANDOM % 10))
 echo "You rolled a $stealth"
 if (($stealth >= 5))
 then
 	echo "No one notices you enter"
 else
	echo "The cook sees you. He thinks you are the dishwasher. You wash dishes for three hours. You receive five gold."
	gold=5
 fi
}


in_tavern(){
 echo "Roll for perception to look around the tavern"
 local per=$(( $RANDOM % 10))
 echo "You rolled a $per"

 if (($per <=4))
 then 
 	echo "You notice a trap door"
 else (($per >=4))
	echo "You hear strange whisperings coming from a trap door in the corner."
 fi
}	

tavern_stealth(){

 if (($tavernpass == 0))
 then
 	if (($tavern_chrfail == 0))
 	then tavern_stealthcheck
 	in_tavern
 	else (($tavern_chrfail == 1))
 	in_tavern
 	fi
 
 else (($tavernpass == 1))
 	in_tavern	
 fi
}

tavern_stealth

read -p "$name would you like to roll for int, str or magic? " trapdoor

trapdoor_int(){
 if (( $roll >=5))
 then 
 	echo "You notice an elven puzzle lock. You solve it successfully."
 	return 1
 else 
 	echo "You notice an elven puzzle lock. You are unable to solve it."
 	read -p "Would you like to roll for str or magic? " try_again
	return 0
 fi
}


trapdoor_str(){
 if (( $roll >=5))
 then 
 	echo "You pull the trapdoor open, breaking its hinges."
	return 1
 else 
 	echo "You attempt to pull open the trapdoor but it doesn't budge."
 	read -p "Would you like to roll for int or magic? " try_again
	return 0
 fi

}

trapdoor_magic(){
 if (( $roll >=5))
 then 
 	echo "You enchant the trapdoor, opening the lock."
 	return 1
 else
 	echo "You whisper a spell but cannot open the trapdoor."
 	read -p "Would you like to roll for int or str? " try_again
 	return 0
 fi
}

open_trapdoor(){
 local roll=$(( $RANDOM % 10))
 echo "You rolled a $roll"

 if [ "$trapdoor" == "int" ]
 then 
 	trapdoor_int
 	open=$?

 elif [ "$trapdoor" == "str" ]
 then 
 	trapdoor_str
 	open=$?

 elif [ "$trapdoor" == "magic" ]
 then 
 	trapdoor_magic
 	open=$?
 fi 
}


open_trapdoor

open_true(){
 if (( $open == 1))
 then
 	echo "You feel a chill as you enter the basement"
 	read -p "Would you like to roll for per or magic to look around? " look_basement
 else (( $open == 0))
 	case $try_again in
	"int") trapdoor_int;;
 	"magic") trapdoor_magic;;
 	"str") trapdoor_str;;
	esac
 fi
}

open_true

in_basement(){
 local roll=$(( $RANDOM % 10))
 echo "You rolled a $roll"

 if [ "$look_basement" == "per" ]
 then
 	if (( $roll >=5))
 	then 
 		echo "Your eyes adjust to the darkness and you notice a treasure chest"
 	else
 		read -p "You notice a torch. Would you like to light it? Yes/no " torch
 	fi
 else [ "$look_basement" == "magic" ]
 	if (( $roll >=5))
 	then
 		echo "You summon a glowing orb of light"
 	else 
 		read -p "Your magical light orb sputters out. From its brief glow you notice a torch on the wall. Would you like to light it? Yes/no " torch
	fi

 fi

}

in_basement






